export const FETCH_USER_LIST = 'FETCH_USER_LIST';

export const FETCH_USER_LIST_REQUEST = 'FETCH_USER_LIST_REQUEST';

export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';

export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR';

export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const UPDATE_USER_CLEAR = 'UPDATE_USER_CLEAR';

export const TRANSTER_REQUEST = 'TRANSTER_REQUEST';

export const TRANSTER_REQUEST_REQUEST = 'TRANSTER_REQUEST_REQUEST';

export const TRANSTER_REQUEST_SUCCESS = 'TRANSTER_REQUEST_SUCCESS';

export const TRANSTER_REQUEST_ERROR = 'TRANSTER_REQUEST_ERROR';

export const TRANSTER_REQUEST_CLEAR = 'TRANSTER_REQUEST_CLEAR';

export const TRANSTER_REQUEST_PENDING = 'TRANSTER_REQUEST_PENDING';

export const TRANSTER_REQUEST_PENDING_REQUEST = 'TRANSTER_REQUEST_PENDING_REQUEST';

export const TRANSTER_REQUEST_PENDING_SUCCESS = 'TRANSTER_REQUEST_PENDING_SUCCESS';

export const TRANSTER_REQUEST_PENDING_ERROR = 'TRANSTER_REQUEST_PENDING_ERROR';

export const TRANSTER_REQUEST_PENDING_CLEAR = 'TRANSTER_REQUEST_PENDING_CLEAR';

export const DELETE_USER = 'DELETE_USER';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const DELETE_USER_CLEAR = 'DELETE_USER_CLEAR';

export const WORKER_LOGS_HISTORY = 'WORKER_LOGS_HISTORY';

export const WORKER_LOGS_HISTORY_REQUEST = 'WORKER_LOGS_HISTORY_REQUEST';

export const WORKER_LOGS_HISTORY_SUCCESS = 'WORKER_LOGS_HISTORY_SUCCESS';

export const WORKER_LOGS_HISTORY_ERROR = 'WORKER_LOGS_HISTORY_ERROR';

export const WORKER_LOGS_HISTORY_CLEAR = 'WORKER_LOGS_HISTORY_CLEAR';

export const USER_COUNT = 'USER_COUNT';

export const USER_COUNT_REQUEST = 'USER_COUNT_REQUEST';

export const USER_COUNT_SUCCESS = 'USER_COUNT_SUCCESS';

export const USER_COUNT_ERROR = 'USER_COUNT_ERROR';

export const ROLE = {
  SUPER_ADMIN: 'Super Admin',
  CR: 'CR',
  NOTIFIER: 'Notifier',
  LAUNCHER: 'Launcher',
  MINISTRY_ADMIN: 'Ministry Admin',
  VIEWER: 'Viewer',
  SECONDARY_ADMIN: 'Secondary Admin'
};
