export const FETCH_TRANSFER_LOGS_LIST = 'FETCH_TRANSFER_LOGS_LIST';

export const FETCH_TRANSFER_LOGS_LIST_REQUEST = 'FETCH_TRANSFER_LOGS_LIST_REQUEST';
export const FETCH_TRANSFER_LOGS_LIST_SUCCESS = 'FETCH_TRANSFER_LOGS_LIST_SUCCESS';
export const FETCH_TRANSFER_LOGS_LIST_ERROR = 'FETCH_TRANSFER_LOGS_LIST_ERROR';

export const STATUS = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const ROLE = {
  SUPER_ADMIN: 'Super Admin',
  CR: 'CR',
  NOTIFIER: 'Notifier',
  LAUNCHER: 'Launcher',
  MINISTRY_ADMIN: 'Ministry Admin',
  SECONDARY_ADMIN: 'Secondary Admin'
};
