export const FETCH_TRANSFER_REQUEST_LIST = 'FETCH_TRANSFER_REQUEST_LIST';

export const FETCH_TRANSFER_REQUEST_LIST_REQUEST = 'FETCH_TRANSFER_REQUEST_LIST_REQUEST';
export const FETCH_TRANSFER_REQUEST_LIST_SUCCESS = 'FETCH_TRANSFER_REQUEST_LIST_SUCCESS';
export const FETCH_TRANSFER_REQUEST_LIST_ERROR = 'FETCH_TRANSFER_REQUEST_LIST_ERROR';

export const UPDATE_TRANSFER_REQUEST = 'UPDATE_TRANSFER_REQUEST';
export const UPDATE_TRANSFER_REQ_REQUEST = 'UPDATE_TRANSFER_REQ_REQUEST';
export const UPDATE_TRANSFER_REQ_SUCCESS = 'UPDATE_TRANSFER_REQ_SUCCESS';
export const UPDATE_TRANSFER_REQ_ERROR = 'UPDATE_TRANSFER_REQ_ERROR';
export const UPDATE_TRANSFER_REQ_CLEAR = 'UPDATE_TRANSFER_REQ_CLEAR';

export const UPDATE_STATUS = {
  APPROVED: 'approved',
  REJECTED: 'rejected'
};

export const ROLE = {
  SUPER_ADMIN: 'Super Admin',
  CR: 'CR',
  NOTIFIER: 'Notifier',
  LAUNCHER: 'Launcher',
  MINISTRY_ADMIN: 'Ministry Admin',
  SECONDARY_ADMIN: 'Secondary Admin'
};
