export const FETCH_USER_APPLICATIONS_LIST = 'FETCH_USER_APPLICATIONS_LIST';
export const FETCH_USER_APPLICATIONS_LIST_REQUEST = 'FETCH_USER_APPLICATIONS_LIST_REQUEST';
export const FETCH_USER_APPLICATIONS_LIST_SUCCESS = 'FETCH_USER_APPLICATIONS_LIST_SUCCESS';
export const FETCH_USER_APPLICATIONS_LIST_ERROR = 'FETCH_USER_APPLICATIONS_LIST_ERROR';

export const UPDATE_USER_APPLICATION = 'UPDATE_USER_APPLICATION';
export const UPDATE_USER_APPLICATION_REQUEST = 'UPDATE_USER_APPLICATION_REQUEST';
export const UPDATE_USER_APPLICATION_SUCCESS = 'UPDATE_USER_APPLICATION_SUCCESS';
export const UPDATE_USER_APPLICATION_ERROR = 'UPDATE_USER_APPLICATION_ERROR';
export const UPDATE_USER_APPLICATION_CLEAR = 'UPDATE_USER_APPLICATION_CLEAR';
