export const FETCH_USER_STATUS_LOGS = 'FETCH_USER_STATUS_LOGS';

export const FETCH_USER_STATUS_LOGS_REQUEST = 'FETCH_USER_STATUS_LOGS_REQUEST';

export const FETCH_USER_STATUS_LOGS_SUCCESS = 'FETCH_USER_STATUS_LOGS_SUCCESS';

export const FETCH_USER_STATUS_LOGS_ERROR = 'FETCH_USER_STATUS_LOGS_ERROR';

export const DATA_UPDATE = 'DATA_UPDATE';

export const DATA_UPDATE_REQUEST = 'DATA_UPDATE_REQUEST';

export const DATA_UPDATE_SUCCESS = 'DATA_UPDATE_SUCCESS';

export const DATA_UPDATE_ERROR = 'DATA_UPDATE_ERROR';

export const ROLE = {
  SUPER_ADMIN: 'Super Admin',
  CR: 'CR',
  NOTIFIER: 'Notifier',
  LAUNCHER: 'Launcher',
  MINISTRY_ADMIN: 'Ministry Admin',
  SECONDARY_ADMIN: 'Secondary Admin'
};
